# Generated by Django 6.0.4 on 2026-04-29 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название плейлиста')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Плейлист',
                'verbose_name_plural': 'Плейлисты',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='catalog.chapter')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='player.playlist')),
            ],
            options={
                'verbose_name': 'Элемент плейлиста',
                'verbose_name_plural': 'Элементы плейлиста',
                'ordering': ['order'],
                'unique_together': {('playlist', 'chapter')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_seconds', models.PositiveIntegerField(default=0, verbose_name='Текущая позиция (сек)')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Прослушана до конца')),
                ('last_listened_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего прослушивания')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='catalog.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс прослушивания',
                'verbose_name_plural': 'Прогрессы',
                'unique_together': {('user', 'chapter')},
            },
        ),
    ]
